#!/usr/bin/env python3
import os
from pathlib import Path

#Game variables
WINDOW_CAPTION = "Flappy Bird"
WINDOW_WIDTH = 910
WINDOW_HEIGHT = 512
WINDOW_FPS = 30 

BIRD_START_POS = (100, 300)
BIRD_FLAP_VELOCITY = -7
BIRD_ACCELERATION = 0.5
BIRD_ANGULAR_SPEED = -7
BIRD_MAX_VELOCITY = 7
BASE_SCROLL_SPEED = 1

current_file_path = Path(__file__).resolve()
current_dir = current_file_path.parent

RESOURCE_SPRITES_PATH = os.path.join(current_dir, "assets", "sprites")

RESOURCE_BACGROUND_WIDTH = 288
RESOURCE_BACGROUND_HEIGHT = 512
RESOURCE_BACGROUND_DAY_PATH     = os.path.join(RESOURCE_SPRITES_PATH, "background-day.png")

RESOURCE_BIRD_WIDTH = 34
RESOURCE_BIRD_HEIGHT = 24
RESOURCE_BLUEBIRD_DOWNFLAP_PATH = os.path.join(RESOURCE_SPRITES_PATH, "bluebird-downflap.png")
RESOURCE_BLUEBIRD_MIDFLAP_PATH  = os.path.join(RESOURCE_SPRITES_PATH, "bluebird-midflap.png")
RESOURCE_BLUEBIRD_UPFLAP_PATH   = os.path.join(RESOURCE_SPRITES_PATH, "bluebird-upflap.png")

RESOURCE_BASE_WIDTH = 336
RESOURCE_BASE_HEIGHT = 112
RESOURCE_BASE_PATH = os.path.join(RESOURCE_SPRITES_PATH, "base.png")

RESOURCE_PIPE_WIDTH = 52
RESOURCE_PIPE_HEIGHT = 320
RESOURCE_PIPE_GREEN_PATH = os.path.join(RESOURCE_SPRITES_PATH, "pipe-green.png")

RESOURCE_FONT_PATH = os.path.join(current_dir, "assets", "font", "04B_19__.TTF")

PIPE_SPAWNER_POS_X = 950
PIPE_SPAWNER_TIMEOUT = 180
PIPE_SPAWNER_POSY_RAND_RANGE_MIN = -RESOURCE_PIPE_HEIGHT + 25
PIPE_SPAWNER_POSY_RAND_RANGE_MAX = -RESOURCE_PIPE_HEIGHT + 275
PIPE_SPAWNER_POSY_GAP = 100

RESOURCE_MESSAGE_WIDTH = 184
RESOURCE_MESSAGE_HEIGHT = 267
RESOURCE_MESSAGE_PATH = os.path.join(RESOURCE_SPRITES_PATH, "message.png")

RESOURCE_GAMEOVER_WIDTH = 192
RESOURCE_GAMEOVER_HEIGHT = 42
RESOURCE_GAMEOVER_PATH = os.path.join(RESOURCE_SPRITES_PATH, "gameover.png")